name: test_image_editor
description: 画像編集のテストアプリ
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

#  riverpod:
  build_runner:
  flutter_riverpod: ^2.4.10
  riverpod_annotation: ^2.3.4
  hooks_riverpod: ^2.4.10

#  freezed:
  freezed: ^2.4.7

#  image_editor:
  image_editor_plus: ^1.0.4
  image_picker: ^1.0.7
  image_gallery_saver: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  riverpod_generator:

flutter:

  uses-material-design: true

  assets:
    - assets/
