import 'package:image_editor_plus/image_editor_plus.dart';


void ImageEditorLocalise() {
  ImageEditor.i18n({
    // 最初の画面
    'Crop': '切り取り',
    'Brush': 'ペンツール',
    'Text': 'テキスト',
    'Link': 'リンク',
    'Flip': '反転',
    'Rotate left': '左回転',
    'Rotate right': '右回転',
    'Blur': 'ぼかし',
    'Filter': 'フィルター',
    'Emoji': '絵文字',
    // 切り取り
    'Freeform': '画面比率',
    // テキスト
    'Insert Your Message': 'メッセージを入力',
    // ぼかし TODO: ちょっと怪しい日本語訳
    'SLIDER FILTER COLOR': 'スライドフィルターカラー',
    'Slider Color': 'スライダーカラー',
    'Blur Radius': 'ぼかし半径',
    'Color Opacity': '色の不透明度',
    'Reset': 'リセット',
    // フィルター TODO: ちょっと怪しい日本語訳
    'No Filter': 'フィルター解除',
    'AddictiveBlue':'アディクティブブルー',
    'AddictiveRed':'アディクティブレッド',
    'Aden':'アデン',
    'Amaro':'アマロ',
    'Ashby':'アシュビー',
    'Brannan':'ブランナン',
    'Brooklyn':'ブルックリン',
    'Charmes':'チャーム',
    'Clarendon':'クラレンドン',
    'Crema':'クレマ',
    'Dogpatch':'ドッグパッチ',
    'Earlybird':'アーリーバード',
    'f1977':'f1977',
    'Gingham':'ギンガム',
    'Ginza':'ギンザ',
    'Hefe':'ヘフェ',
    'Helena':'ヘレナ',
    'Hudson':'ハドソン',
    'Inkwell':'インクウェル',
    'Juno':'ジュノ',
    'Kelvin':'ケルビン',
    'Lark':'ラルク',
    'LoFi':'ロファイ',
    'Ludwig':'ルートヴィヒ',
    'Maven':'メイブン',
    'Mayfair':'メイフェア',
    'Moon':'ムーン',
    'Nashville':'ナッシュビル',
    'Perpetua':'ペルペルア',
    'Reyes':'レイエス',
    'Rise':'ライズ',
    'Sierra':'シエラ',
    'Skyline':'スカイライン',
    'Slumber':'まどろみ',
    'Stinson':'スティンソン',
    'Sutro':'スートロ',
    'Toaster':'トースター',
    'Valencia':'バレンシア',
    'Vesper':'ヴェスパー',
    'Walden':'ウォルデン',
    'Willow':'ウィロー',
    'xProII':'xProII',
    // 絵文字
    'Select Emoji': '絵文字を選択',
    'SIZE ADJUST': 'サイズ調整',
    'Remove': '削除',
  });
}
